spring:
  datasource:
    url: jdbc:mysql://localhost/patient-service
    username: root
    password: 111111
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/PatientService
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/PatientService
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: patient-service
            client-secret: 6c5XKj0Naz4It3lKLstxQVphlXTwR3tB
            scope: openid
server:
  port: 8081
practitioner:
  username: practitioner
  password: practitioner
